M48
; DRILL file {KiCad (6.0.0)} date Tue Jan 31 14:46:16 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-31T14:46:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X78.105Y-98.425
X78.105Y-146.685
X160.645Y-98.425
X160.645Y-146.685
T0
M30
