M48
; DRILL file {KiCad (6.0.0)} date Wed Nov  9 00:04:34 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T00:04:34-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X78.105Y-98.425
X78.105Y-146.685
X160.645Y-98.425
X160.645Y-146.685
T0
M30
